---
jobs:
- name: bootstrap
  public: false
  plan:
  - task: set-pipelines
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: echo
        args: [hello world one - {{environment}}]
