---

#
# The task will toggle the state of the environment
#

platform: linux

image_resource:
  type: docker-image
  source:
    repository: appbricks/automation-tools

inputs:
- name: job-info

run:
  path: /bin/bash
  args:
  - -c
  - |
    set -euo pipefail
    
    mc config host add auto $AUTOS3_URL $AUTOS3_ACCESS_KEY $AUTOS3_SECRET_KEY

    # The job info file must have the following variables
    # retrieve from the job execution for which an email
    # needs to be sent.
    #
    # BUILD_ID=...
    # BUILD_NAME=...
    # BUILD_JOB_NAME=...
    # BUILD_PIPELINE_NAME=...
    # BUILD_TEAM_NAME=...
    # ATC_EXTERNAL_URL=...
    # MESSAGE=
    #

    source job-info/job_info
    echo "export JOB_STATUS='${JOB_STATUS}'" >> job-info/job_info
    echo "export SUBJECT='${SUBJECT_PRE} - ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'" >> job-info/job_info

    if [[ -e job-info/job_message ]]; then
      echo "export MESSAGE=$(cat job-info/job_message | base64)
    fi
    
    mc cp job-info/job_info auto/notifications/email-queue/job_email-$(cat /proc/sys/kernel/random/uuid)

params:
  AUTOS3_URL:
  AUTOS3_ACCESS_KEY:
  AUTOS3_SECRET_KEY:
  SUBJECT_PRE:
  JOB_STATUS:
