---

#
# The task will toggle the state of the environment
#

platform: linux

image_resource:
  type: docker-image
  source:
    repository: appbricks/automation-tools

inputs:
- name: job_info

run:
  path: /bin/bash
  args:
  - -c
  - |
    mc config host add auto $AUTOS3_URL $AUTOS3_ACCESS_KEY $AUTOS3_SECRET_KEY

    source job_info/job_info
    echo "SUBJECT='${SUBJECT_PRE} - ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'" > job_info/job_info

    mc cp job_info/job_info auto/$BUCKET/$UPLOAD_PATH/job_email-$(cat /proc/sys/kernel/random/uuid)

params:
  BUCKET:
  UPLOAD_PATH:
  AUTOS3_URL:
  AUTOS3_ACCESS_KEY:
  AUTOS3_SECRET_KEY:
  SUBJECT_PRE:
