---

#
# The task will toggle the state of the environment
#

platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfseceng/email-resource

inputs:
- name: automation
- name: emails

run:
  path: automation/lib/inceptor/tasks/send_job_emails/task.sh

params:
  AUTOS3_URL:
  AUTOS3_ACCESS_KEY:
  AUTOS3_SECRET_KEY:
