- type: replace
  path: /jobs/-
  value:
    name: notifications
    public: false
    serial: true
    plan:
    - get: automation
    - task: prepare_job_email
      file: ((pipeline_automation_path))/tasks/prepare_job_email/task.yml
      params:
        CONCOURSE_URL: ((concourse_url))
        CONCOURSE_USER: ((concourse_user))
        CONCOURSE_PASSWORD: ((concourse_password))
        AUTOS3_URL: ((autos3_url))
        AUTOS3_ACCESS_KEY: ((autos3_access_key))
        AUTOS3_SECRET_KEY: ((autos3_secret_key))
        SMTP_HOST: ((smtp_host))
        SMTP_PORT: ((smtp_port))
        EMAIL_FROM: ((automation_email))
        EMAIL_TO: ((notification_email))      
    - task: send_job_emails
      file: ((pipeline_automation_path))/tasks/send_job_emails/task.yml
      params:
        AUTOS3_URL: ((autos3_url))
        AUTOS3_ACCESS_KEY: ((autos3_access_key))
        AUTOS3_SECRET_KEY: ((autos3_secret_key))
